Initial version of the SQL adapter
BHoM/SQL_Toolkit pull request #2
Opened 2021-03-11 08:48 UTC by adecler

### Issues addressed by this PR

Closes #1

See issue for more details

The table that links the tables to types has to be named `_tableTypes` and should contains two properties as follows:

![image](https://user-images.githubusercontent.com/16853390/110759608-c3f97200-8288-11eb-9c4d-4759309e53f5.png)

This is only required if you want your tables to behave in a strong-typed manner but will work without it or if only some of your table are type-strong. 

### Test files
https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/SQL_Toolkit/%231-InitialVersion?csf=1&web=1&e=9az7l5

2021-03-11 09:12 UTC, FraserGreenroyd commented
@BHoMBot check project compliance

2021-03-11 09:26 UTC, adecler commented
@BHoMBot check project-compliance

2021-03-11 09:30 UTC, FraserGreenroyd commented
@BHoMBot check core

2021-03-11 15:48 UTC, FraserGreenroyd commented on SQL_oM/SQL_oM.csproj
> +    <Reference Include="BHoM" />
```suggestion
    <Reference Include="BHoM">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>C:\ProgramData\BHoM\Assemblies\BHoM.dll</HintPath>
    </Reference>
```

2021-03-11 15:49 UTC, FraserGreenroyd commented
@BHoMBot check core

2021-03-11 15:57 UTC, FraserGreenroyd commented
@BHoMBot check compliance

2021-03-11 16:02 UTC, FraserGreenroyd commented
@BHoMBot fix copyright headers ref. 2087696624

2021-03-11 16:04 UTC, FraserGreenroyd commented
@BHoMBot fix project file ref. 2087696090

2021-03-11 16:05 UTC, FraserGreenroyd commented
@BHoMBot check compliance

2021-03-11 16:15 UTC, al-fisher commented
Thanks for updating the SQL_oM.csproj error @FraserGreenroyd 🙏   - was just looking at that

2021-03-11 16:26 UTC, FraserGreenroyd commented
@BHoMBot check core

2021-03-11 18:32 UTC, al-fisher requested changes
This is looking good. Tested pushing and pulling to various dummy tables - and behaving as expected.
One minor issue @adecler - the Push returns `success false` even when it was indeed successful.
Will continue to test some more

2021-03-12 02:13 UTC, adecler commented
@BHoMBot check compliance

2021-03-12 02:14 UTC, adecler commented
@BHoMBot check core

2021-03-12 02:21 UTC, adecler commented
@BHoMBot check core

2021-03-12 02:21 UTC, adecler commented
@BHoMBot check compliance

2021-03-19 16:44 UTC, tg359 commented
Me and @michaelhoehn had a go at pushing some random stuff to some tables and encountered the following issues. I'm not sure whether these should be full Issue issues, or could be handled easier here:

- Deserialisation of BHoM_Guid from the SQL DB fails as the field name BHoM_Guid  is being stored as a string in the DB, and the custom object being created from the Pull is being given the `string` version not a `Guid`. Could this be made to automatically convert the BHoM_Guid field into a Guid dtype?
- Can a type-strong table be created from a set of single dtype objects? Something like an option in the pushConfig to create the table if it doesn't exist would be useful for setup (along with the associate methods to make sure the attributes/fields match if it already exists).

2021-04-07 07:14 UTC, adecler commented
@tg359, @michaelhoehn ,

Thanks for checking out the SQL adapter 😄 .

- I have checked that Guid can be pushed and pulled correctly and they are indeed working as expected BUT you have to make sure their datatype is defined as `uniqueidentifier` in the schema, not as a string.

- It is definitely possible to automatically create tables if they don't already exist. If you look at the code from this PR, you will notice a few `CreateTable` methods that are doing just that. The key question is "should we ?". We already have MongoDB as a database that can accept any type of data. And the Mongo adapter will also create the collection if it doesn't already exist. The SQL database is meant for a type different type of use cases: storing specific results (with curated schema) with the purpose the visualise/explore/communicate those results. With that in mind, we expect most of the objects pushed to SQL being of the `IResult` type and specifically designed for being stored in a database. That means, for example, flat data (i.e. only primitive properties) that can easily be processed by something like PowerBI. So, I am not saying we will never facilitate the creation of tables. But I would like it to be a manual, conscious, and controlled process for now (until we have use cases that justify more flexibility).

I hope that all make sense. I have created a document to collect our user stories [here](https://burohappold.sharepoint.com/:f:/r/sites/Direction/designtechnology/RandDWishlist/00217_SQL%20Adapter?csf=1&web=1&e=WTW02y). Feel free to add your use cases to it.

2021-04-20 02:21 UTC, adecler commented
@FraserGreenroyd , @al-fisher , could you update your review of this PR, please ?

2021-04-27 14:54 UTC, FraserGreenroyd approved these changes
This looks fine from my testing now, sorry for the delay @adecler . I believe @tg359 has been testing more as well in addition to your testing :smile:

2021-04-27 14:54 UTC, FraserGreenroyd commented
@BHoMBot check core

2021-04-27 16:00 UTC, FraserGreenroyd commented
@BHoMBot check core

2021-04-27 16:30 UTC, FraserGreenroyd commented
@BHoMBot check core

2021-04-28 01:31 UTC, adecler commented
Thanks @FraserGreenroyd :thumb:

@al-fisher , your review is still blocking the PR despite your request being addressed (see commit on the 12th of March). Could you update your review please ?

@tg359 , it would be great if you could also provide a review before this is merged.

2021-04-28 06:57 UTC, al-fisher commented
Perfect 
Thanks @adecler 
Yes - have dismissed my review.

2021-04-28 08:43 UTC, tg359 approved these changes
Tested using the sample script and this worked for me.

2021-04-28 09:03 UTC, merged